import { THEME_SLUGS, type ThemeCopy, type ThemeRecord, type ThemeSection, type ThemeSlug } from "./types";

export { THEME_SLUGS } from "./types";
export type { ThemeCopy, ThemeRecord, ThemeSection, ThemeSlug } from "./types";

type Profile = Omit<ThemeCopy, "sections"> & { vision: string; palette: string; home: string; task: string };
function enSections(name: string, p: Profile): ThemeSection[] { return [
  { title: "Design intent", paragraphs: [p.vision, `${name} is intentionally abstract so it can establish atmosphere without introducing a face, character, logo, or narrative object that competes with work. The composition is not a screenshot and contains no simulated Codex controls. Its visual hierarchy comes from scale, light, and empty space: a restrained left field supports content while the right-side form gives the eye a destination. This makes the file useful as a background rather than a poster that happens to sit behind an application.`] },
  { title: "Palette and material", paragraphs: [p.palette, `Color is concentrated around the focal form and fades toward near-black across the reading zone. The transition avoids tiny high-contrast texture, generated lettering, and repeated particles that can resemble interface states. Smooth gradients may show differently across monitors, so inspect the actual app at normal brightness. If a display exaggerates the highlight, reduce background intensity or strengthen the existing content panel rather than adding new decorative detail.`] },
  { title: "Home-view composition", paragraphs: [p.home, p.homeCompositionNotes] },
  { title: "Task-view readability", paragraphs: [p.task, p.taskCompositionNotes] },
  { title: "Creation and source record", paragraphs: [`This asset was generated specifically for CodexSkin on 20 July 2026 from an original prompt written for this collection. The prompt required a 20:9 abstract wallpaper, a dark low-detail left 55%, right-side visual concentration, a quiet bottom region, and no people, text, logos, trademarks, borders, or interface elements. CodexSkin Editorial reviewed the output at full size, rejected any brand dependency, and exported a compressed JPEG from the retained generated PNG. The site repository records the public filename and this page records the source method.`, `The generation record establishes the practical provenance used by this site; it is not a claim about every possible legal issue in every jurisdiction. The artwork does not copy the archived third-party demonstration composites and does not include OpenAI or Codex marks. The original generation file remains separate from the web export so compression can be repeated without accumulating artifacts. Corrections about this record can be sent through the Contact page.`] },
  { title: "License and reuse", paragraphs: [`The downloadable background is offered under CodexSkin-Theme-1.0. Personal and commercial use, modification, and redistribution are allowed under the terms in the adjacent license file, provided recipients do not imply that OpenAI, Codex, or a third-party tool endorses their use. The license covers only the CodexSkin-created wallpaper file. It does not license product names, official application screenshots, third-party installers, source code, or the archived demonstration images elsewhere in the repository.`, `Keep the license or a clear link with redistributed copies, and describe modifications honestly. Do not add an official-looking logo, false endorsement, protected character, or portrait and continue to present the result as the unchanged CodexSkin original. If you combine the image with material from another source, you are responsible for confirming that source permits the resulting use. The flags for this release are: no portrait, no branded character, and no trademark embedded in the artwork.`] },
  { title: "Apply and verify", paragraphs: [`Download the JPEG, keep an untouched copy, and follow the independent background-composition and platform guides. CodexSkin does not bundle this asset with a third-party installer. Import a copy through the current upstream-documented Windows or macOS interface, then inspect home and a populated task. Check headings, muted text, code, links, focus, composer boundaries, wide and narrow windows, and the normal restore path. A visible wallpaper is not enough; native controls must remain readable and interactive.`, `If ${name} is too bright on your display, adjust a working copy rather than the repository master. Preserve the left reading field and right focal placement when cropping. Do not move the main highlight into the bottom composer band. Record the export used so you can return to a known result, and restore official appearance before diagnosing unrelated Codex problems.`] },
]; }
function zhSections(name: string, p: Profile): ThemeSection[] { return [
  { title: "设计意图", paragraphs: [p.vision, `${name} 采用抽象构图，是为了建立氛围而不引入会与工作内容竞争的人脸、角色、Logo 或叙事物体。图片不是截图，也没有模拟 Codex 控件。视觉层级只来自尺度、光线和留白：左侧克制区域支持正文，右侧形体提供视线终点。这让素材首先是一张可长期使用的背景，而不是偶然放在应用后面的海报。`] },
  { title: "配色与材质", paragraphs: [p.palette, `颜色集中在右侧焦点周围，并向左侧近黑阅读区逐渐衰减。过渡中避免了细小高对比纹理、生成文字和重复粒子，防止它们看起来像界面状态。不同显示器对渐变和高光的呈现会不同，应在日常亮度下检查真实应用；如果高光过强，应降低工作副本亮度或使用现有内容面板，而不是增加更多装饰细节。`] },
  { title: "首页构图", paragraphs: [p.home, p.homeCompositionNotes] },
  { title: "任务页可读性", paragraphs: [p.task, p.taskCompositionNotes] },
  { title: "生成与来源记录", paragraphs: [`该素材由 CodexSkin 在 2026 年 7 月 20 日根据本合集原创提示词专门生成。提示词要求 20:9 抽象壁纸、左侧 55% 暗色低细节、视觉集中在右侧、底部保持安静，并禁止人物、文字、Logo、商标、边框与界面。CodexSkin 编辑部检查了全尺寸输出，确认不依赖品牌视觉，再从保留的生成 PNG 导出压缩 JPEG。站点仓库记录公开文件名，本页记录来源方法。`, `这份生成记录说明本站采用的实际来源流程，并不替代不同地区的专业法律判断。图片没有复制仓库中归档的第三方演示合成图，也不包含 OpenAI 或 Codex 标识。保留原始生成文件与网页导出分离，可以在不累积压缩损失的情况下重新输出。来源记录需要更正时，可通过 Contact 页面联系。`] },
  { title: "许可与再利用", paragraphs: [`可下载背景采用 CodexSkin-Theme-1.0。按照相邻许可文件，允许个人与商业使用、修改和再分发，但不得暗示 OpenAI、Codex 或第三方工具对使用行为背书。许可只覆盖 CodexSkin 创作的壁纸文件，不覆盖产品名称、官方应用截图、第三方安装程序、源码或仓库中归档的演示图。`, `再分发时应保留许可或清楚链接，并如实说明修改。不要加入官方式 Logo、虚假背书、受保护角色或肖像后，仍把结果描述为未修改的 CodexSkin 原作。与其他来源素材组合时，应另行确认对方许可。此版本权利标记为：无人像、无品牌角色、图片中无商标。`] },
  { title: "应用与验证", paragraphs: [`下载 JPEG 并保留未修改副本，再阅读本站背景构图和平台指南。CodexSkin 不会把素材与第三方安装程序打包。通过当前上游文档记录的 Windows 或 macOS 界面导入工作副本，然后检查首页和内容丰富的任务页，包括标题、弱化文字、代码、链接、焦点、输入框边界、宽窄窗口和恢复流程。看到壁纸不等于通过，原生控件必须继续清楚且可交互。`, `如果 ${name} 在你的显示器上过亮，应修改工作副本而不是仓库母版。裁切时保留左侧阅读区和右侧焦点，不要把高光移动到底部输入框带。记录所用导出版本，方便回到稳定结果；排查与主题无关的问题前，先恢复官方外观。`] },
]; }

const profiles: Record<ThemeSlug, { image: string; en: Profile; zh: Profile }> = {
  "dark-aurora": { image: "/original-themes/dark-aurora.jpg", en: { name: "Dark Aurora", description: "Emerald and cyan aurora ribbons over a quiet midnight reading field.", alt: "Original dark ultrawide wallpaper with emerald aurora light concentrated on the right", homeCompositionNotes: "The left field remains nearly uniform beneath home titles; the aurora starts beyond the midpoint and stays recognizable after a wide crop.", taskCompositionNotes: "Task text sits over navy-black space while the brighter ribbons remain outside the main reading column and above the composer.", vision: "Dark Aurora turns a natural light phenomenon into a controlled directional gesture. The ribbon enters from the upper-right, curves toward the central vertical zone, and dissolves before it reaches the left reading field. Small star-like traces are restricted to the focal side, while the opposite half stays calm enough for headings, project names, and long task history.", palette: "Midnight navy and blue-black form the base. Emerald provides the primary energy, cyan outlines movement, and a small amount of deep teal connects the highlight to the dark field. There is no pure white focal point, which helps prevent the aurora from overpowering interface text.", home: "On a wide home crop, the aurora behaves as a visual counterweight to titles rather than a banner illustration that must be read literally. Its brightest curve sits inside the right third and the left title area receives only a faint blue atmosphere.", task: "In a task, the long diagonal flow stays outside the core reading column. The lower portion is deliberately dark, so the composer does not cut through a meaningful object and status messages retain contrast." }, zh: { name: "暗夜极光", description: "翡翠与青蓝极光集中在右侧，左侧保留午夜阅读区。", alt: "原创暗色超宽壁纸，翡翠极光集中在右侧", homeCompositionNotes: "左侧在首页标题下保持近似均匀，极光从中线以右开始，并能在超宽裁切中保持识别。", taskCompositionNotes: "任务正文位于深蓝黑区域，较亮光带避开主阅读列，并保持在输入框上方。", vision: "暗夜极光把自然光现象整理成受控方向线。光带从右上方进入，弯向中央垂直安全区，并在触及左侧阅读区前消散。少量星点只留在焦点侧，另一半保持安静，能够承接标题、项目名和长任务历史。", palette: "午夜蓝与蓝黑构成底色，翡翠提供主要能量，青蓝勾勒运动，少量深青把高光连接到暗区。画面没有纯白焦点，避免极光压过界面文字。", home: "在超宽首页裁切中，极光是标题的视觉配重，而不是必须完整阅读的横幅插画。最亮曲线位于右侧三分之一，左侧标题区只有轻微蓝色气氛。", task: "进入任务页后，长对角线仍然位于核心阅读列之外。下部刻意保持暗色，使输入框不会切断关键物体，状态信息也能维持对比。" } },
  "warm-graphite": { image: "/original-themes/warm-graphite.jpg", en: { name: "Warm Graphite", description: "Copper-lit graphite planes with a restrained architectural rhythm.", alt: "Original graphite ultrawide wallpaper with warm copper geometric planes on the right", homeCompositionNotes: "The large planes create a clear right anchor while the left title zone remains a matte, nearly texture-free black gradient.", taskCompositionNotes: "Geometric edges stay outside the main text column; the floor reflection is subdued before it reaches the composer band.", vision: "Warm Graphite uses folded architectural planes instead of a recognizable object. The arrangement feels engineered but does not imitate interface panels. Forms overlap on the right at several scales, creating depth and a stable diagonal rhythm. The left half is intentionally unfinished in the visual sense: it provides breathable matte darkness rather than another decorative scene.", palette: "Charcoal, graphite, and near-black carry most of the frame. Copper and amber appear only along selected edges and interior gaps, producing warmth without turning the background orange. Material texture is broad and soft, so it reads as surface character at full size rather than granular noise behind small text.", home: "The home layout benefits from the contrast between solid reading space and the concentrated architectural cluster. Large titles can occupy the left without crossing a highlight, while the right forms keep the banner from feeling empty.", task: "In task use, the straight edges could be distracting if centered, so they remain to the right of the reading path. The deepest lower tones support the composer and reduce conflict with code or diagnostic text." }, zh: { name: "暖石墨", description: "铜色边光照亮右侧石墨折面，形成克制的建筑节奏。", alt: "原创石墨超宽壁纸，暖铜色几何折面集中在右侧", homeCompositionNotes: "大尺度折面形成右侧锚点，左侧标题区保持哑光、近乎无纹理的黑色渐变。", taskCompositionNotes: "几何边缘避开主文字列，地面反射在进入底部输入框区域前已经明显减弱。", vision: "暖石墨使用折叠建筑平面，而不是可识别物体。右侧形体以不同尺度重叠，形成工程感和稳定对角节奏，却不会模仿界面面板。左半在视觉上刻意不完成，用可呼吸的哑光暗色代替另一组装饰场景。", palette: "炭黑、石墨和近黑占据主要画面，铜色与琥珀只出现在少量边缘和内部缝隙，带来温度而不让背景整体变橙。材质纹理宽阔柔和，全尺寸下体现表面感，缩小后不会成为小字后的颗粒噪声。", home: "首页利用了完整阅读空间与集中建筑簇之间的对比。大标题可以停留在左侧而不穿过高光，右侧折面又让横幅不显空洞。", task: "任务页中直线若居中会产生干扰，因此全部保持在阅读路径右侧。下部最深色调承接输入框，并减少与代码和诊断文字的冲突。" } },
  "quiet-ocean": { image: "/original-themes/quiet-ocean.jpg", en: { name: "Quiet Ocean", description: "A single teal wave rises from a low-detail blue-black horizon.", alt: "Original blue ultrawide wallpaper with a single teal wave concentrated on the right", homeCompositionNotes: "The wave crest occupies the right third; the left horizon stays low, dark, and simple beneath home navigation and titles.", taskCompositionNotes: "The bright crest remains outside the main reading field, while the lower water becomes a smooth dark base behind the composer.", vision: "Quiet Ocean is built around one broad wave rather than a busy seascape. The horizon is deliberately low and nearly featureless, allowing the left two-thirds to act as open reading air. The wave rises on the right with enough scale to remain recognizable after cropping but contains no animal, vessel, coastline, or narrative detail that could demand attention.", palette: "Blue-black establishes depth, deep navy separates sky and water, and teal appears only around the crest and distant glow. The highlight is diffuse instead of specular, so it feels luminous without becoming a white patch. Subtle horizontal motion exists near the bottom but remains large enough not to interfere with small text.", home: "On home, the low horizon keeps project and navigation elements clear. The crest provides a friendly directional sweep toward the center while stopping before the title zone, producing motion without putting a hard edge behind words.", task: "For task reading, the water surface is intentionally smooth and dark across the left and center. The wave body sits to the right, and the bottom band loses detail so the composer does not conceal the image’s meaning." }, zh: { name: "静海", description: "一束青色海浪从深蓝黑低细节地平线右侧升起。", alt: "原创蓝色超宽壁纸，单一青色海浪集中在右侧", homeCompositionNotes: "浪峰位于右侧三分之一，左侧地平线保持低、暗和简洁，适合首页导航与标题。", taskCompositionNotes: "明亮浪峰避开主阅读区，下方海水渐变为平滑暗色，承接底部输入框。", vision: "静海只使用一束宽阔海浪，而不是拥挤海景。地平线很低且几乎没有细节，使左侧约三分之二成为开放阅读空气。右侧浪峰尺度足够大，在裁切后仍可识别，但没有动物、船、海岸或需要持续关注的叙事细节。", palette: "蓝黑建立深度，深海军蓝区分天空与海面，青色只出现在浪峰和远处微光。高光是扩散光而不是刺眼反射，因此有亮度却不会形成白色斑块。下部存在轻微横向运动，但尺度足够大，不会干扰小字。", home: "首页中低地平线让项目与导航保持清楚，浪峰向中央形成友好方向线，却在标题区前停止，提供运动感而不把硬边放在文字后面。", task: "任务阅读时，左侧和中央海面刻意平滑暗沉。浪体保持在右侧，底部细节进一步消失，使输入框不会遮掉画面含义。" } },
  "violet-glass": { image: "/original-themes/violet-glass.jpg", en: { name: "Violet Glass", description: "Translucent violet arcs form a luminous right-side glass sculpture.", alt: "Original violet ultrawide wallpaper with translucent glass arcs on the right", homeCompositionNotes: "The sculpture stays fully within the right half and the left title region transitions through an uninterrupted black-violet gradient.", taskCompositionNotes: "Arc intersections remain away from the text column, and the floor glow fades before the lower composer obscures it.", vision: "Violet Glass treats transparency as a large sculptural gesture. Several arcs overlap on the right to create depth without forming a letter, logo, character, or interface outline. Their outer silhouette remains contained, while the left side is a continuous field with no secondary object. The result is expressive at wide scale but predictable behind dense content.", palette: "Black-violet is the base, indigo defines depth, and restrained magenta edge light separates the glass layers. Highlights trace only a few curves and never form a repeated grid. Transparency is simulated through broad tonal overlap rather than fine refraction, keeping the image smooth when compressed and preventing glass texture from becoming reading noise.", home: "The wide home surface presents the sculpture as a single right-side event. Its tallest arc has enough top clearance for cropping, and the uninterrupted left gradient gives large headings a consistent background.", task: "A task crop can remove some outer glass without destroying the composition because no single intersection carries meaning. The darkest central-left area remains stable behind paragraphs, and the bottom reflection is quiet enough for the composer." }, zh: { name: "紫晶玻璃", description: "半透明紫色弧面在右侧组成发光玻璃雕塑。", alt: "原创紫色超宽壁纸，半透明玻璃弧面集中在右侧", homeCompositionNotes: "雕塑完整停留在右半区，左侧标题区域通过连续黑紫渐变保持完整。", taskCompositionNotes: "弧面交点远离文字列，地面微光在底部输入框遮挡前已经渐弱。", vision: "紫晶玻璃把透明感处理成大尺度雕塑手势。多条弧面在右侧重叠形成深度，却不会组成字母、Logo、角色或界面轮廓。外部剪影保持集中，左侧则是没有第二物体的连续空间，因此超宽时有表现力，进入密集任务后又具有可预测性。", palette: "黑紫是底色，靛蓝建立深度，克制的洋红边光分离玻璃层。高光只勾勒少量曲线，不形成重复网格。透明感来自大面积明暗叠加，而不是细碎折射，压缩后仍平滑，也避免玻璃纹理成为阅读噪声。", home: "首页将雕塑呈现为单一右侧事件。最高弧线保留足够顶部裁切余量，连续左侧渐变为大标题提供稳定背景。", task: "任务裁切即使移除部分外侧玻璃，也不会破坏构图，因为没有单一交点承载含义。中央偏左深色区稳定承接正文，底部反射足够安静，适合输入框。" } },
};

export const THEMES: ThemeRecord[] = THEME_SLUGS.map((slug) => {
  const profile = profiles[slug];
  return { slug, imagePath: profile.image, creator: "CodexSkin Editorial", creationDate: "2026-07-20", sourceMethod: "AI-generated specifically for CodexSkin from an original prompt; reviewed and exported by CodexSkin Editorial.", license: { id: "CodexSkin-Theme-1.0", href: "/original-themes/LICENSE.md" }, commercialUse: true, redistribution: true, flags: { trademark: false, character: false, portrait: false }, copy: { en: { ...profile.en, sections: enSections(profile.en.name, profile.en) }, zh: { ...profile.zh, sections: zhSections(profile.zh.name, profile.zh) } } };
});
export function getTheme(slug: ThemeSlug) { return THEMES.find((theme) => theme.slug === slug)!; }
export function isThemeSlug(slug: string): slug is ThemeSlug { return (THEME_SLUGS as readonly string[]).includes(slug); }
