import type { ArticleContent, ArticleKey, ArticleSection } from "./types";

const section = (id: string, title: string, text: string, items: string[]): ArticleSection => ({ id, title, blocks: [{ type: "paragraph", text }, { type: "list", items }] });
const article = (value: Omit<ArticleContent, "reviewedDate" | "authorLabel" | "evidenceLabel">): ArticleContent => ({ ...value, reviewedDate: "2026-07-20", authorLabel: "CodexSkin Editorial", evidenceLabel: "First-party practice note: this article separates CodexSkin observations from facts attributed to the upstream repository. It is independent guidance, not OpenAI documentation." });

export const enArticles: Record<ArticleKey, ArticleContent> = {
  "background-image-composition": article({
    key: "background-image-composition", category: "guides", slug: "background-image-composition",
    seo: { title: "Codex Background Image Composition Guide", description: "Design a 20:9 Codex background with safe subject placement, low-detail reading space, crop checks, and a practical source-image prompt." },
    eyebrow: "Original design guide", h1: "Codex Background Image Composition: A Practical Safe-Zone Guide", summary: "Turn one source image into a usable home banner and task background by composing for shared safe zones instead of a single perfect screenshot.",
    sections: [
      section("two-surfaces", "Start with the two-surface problem", "A Codex background is judged in two different layouts. The home view behaves like an ultrawide banner with large headings, cards, and open horizontal space. A task view is taller and denser: paragraphs, code, status text, navigation, and the bottom composer can occupy most of the visible frame. One image is cropped, scaled, and covered differently by those surfaces. Designing only against a home screenshot often produces a task background with a missing face, a horizon through the text, or a key object under the composer. Start with the shared constraints and treat visual drama as a secondary goal. The image should support sustained reading before it decorates an empty screen.", ["Test both a populated task and the home view.", "Use the window sizes you actually work in.", "Keep a master image outside the theme directory.", "Change one composition variable per revision."]),
      section("canvas", "Use 20:9 as a useful working canvas", "A 20:9 source gives enough horizontal room for the wide home treatment without forcing the subject into the reading column. It is a working recommendation from CodexSkin practice, not an official file requirement. Begin at least 2000 pixels wide when your source allows it, preserve the original aspect ratio during generation or layout, and export a high-quality copy for import. Do not stretch a 16:9 photo merely to reach the ratio; extend, recrop, or redesign it so shapes and faces remain natural. Before import, also create a temporary 16:9 preview. That second crop approximates the pressure a task layout can place on the top, sides, and focal subject.", ["Keep the original uncropped source.", "Preview 20:9 and 16:9 before import.", "Avoid upscaling a small noisy image.", "Version exports instead of overwriting them."]),
      section("subject-zone", "Place the focal subject inside the right-side safe zone", "For a portrait, place the face center around 70% to 82% of the canvas width and 35% to 50% of its height. Aim near 45% vertically as a balanced first attempt, keep the complete head visible, and limit total subject height to roughly 45% of the frame. These ranges leave headroom for cropping and move visual weight away from the left reading area. The same idea applies without a person: position a product, architectural form, planet, bright cloud, or abstract focal mass in the right third. Do not push it against the edge. Responsive crops can remove more than a static mockup suggests, so retain quiet padding on the subject’s outer side.", ["Face or focal center: 70%–82% across.", "Vertical center: 35%–50%, often near 45%.", "Subject height: no more than about 45%.", "Preserve headroom and right-edge padding."]),
      section("negative-space", "Reserve the left 55% for readable negative space", "Negative space is not simply empty black pixels. It is an area with controlled brightness, limited texture, slow gradients, and no elements that look like letters or controls. Reserve approximately the left 55% of the source as a dark, low-detail reading field. Soft atmospheric color, broad shadows, or a restrained gradient can keep the image alive without fighting headings and task text. Avoid stars, foliage, hair, city windows, tiny particles, and synthetic pseudo-text in this area. They create local contrast that intersects letter shapes. If the background remains busy after blur, simplify the source or reduce the tonal range rather than expecting interface overlays to solve every conflict.", ["Prefer broad shapes over tiny texture.", "Keep bright edges out of text columns.", "Remove generated pseudo-text and symbols.", "Check muted text, not only headings."]),
      section("composer", "Treat the bottom composer region as unavailable", "The task composer covers part of the lower image and visually dominates the bottom edge. Keep faces, hands, logos, horizon lines, captions, and the decisive part of a silhouette away from that region. Texture may continue behind it, but the composition should still make sense when the lower band is hidden. A useful test is to place a temporary rectangle over the bottom 18% to 24% of your preview. If the story or balance collapses, move the focal elements upward or reduce their scale. This rule also improves narrow windows, where the composer occupies a larger percentage of the available height and horizontal cropping can pull the subject closer to the input area.", ["Mask the bottom 18%–24% during preview.", "Move meaningful elements upward.", "Test the narrowest desktop window you use.", "Do not bake UI chrome into the source."]),
      section("prompt", "Generate a source, then review rather than trusting the prompt", "A practical generator prompt is: 20:9 ultrawide cinematic desktop wallpaper, a small subject in the right third, complete head and generous headroom, face center at 70% to 82% of canvas width and about 45% of canvas height, subject no taller than 45%, left 55% dark low-detail negative space, key subject inside the central vertical safe zone, important details away from the bottom composer, restrained texture, no text, logo, border, or interface. The prompt establishes intent but cannot guarantee anatomy, crop, licensing, or readability. Inspect the full-resolution result, remove accidental marks, confirm your right to use it, compare both crops, import a copy, and repeat the real interface check before keeping it.", ["Reject accidental text, marks, and UI shapes.", "Confirm image rights before publishing.", "Compare home and task after import.", "Regenerate or edit when either surface fails."]),
    ], related: ["readability-and-contrast", "image-rights-and-licensing", "theme-not-visible"],
  }),
  "readability-and-contrast": article({
    key: "readability-and-contrast", category: "guides", slug: "readability-and-contrast",
    seo: { title: "Codex Theme Readability and Contrast Guide", description: "Evaluate background luminance, texture, negative space, composer overlap, focus states, and real task readability before keeping a Codex theme." },
    eyebrow: "Original usability guide", h1: "Readability and Contrast for Codex Themes", summary: "A theme is successful only when code, long task history, controls, and focus states remain easy to perceive during real work.",
    sections: [
      section("readability-goal", "Define readability as sustained work, not a hero screenshot", "A polished home screenshot is a weak readability test because it contains little text and usually shows the image at its most flattering crop. Real work adds long paragraphs, code blocks, links, status messages, error states, menus, and a composer. Readability means those elements remain quickly distinguishable after minutes of use, not merely visible when you stare at them. Begin with ordinary tasks that contain a representative mixture of content. Scroll so different text passes over several background regions. Check at normal viewing distance and normal display brightness. If you must lean closer, hunt for boundaries, or repeatedly select text to read it, the theme is imposing a cost that a better source image can remove.", ["Use a long, representative task.", "Check normal viewing distance and brightness.", "Scroll content across multiple background regions.", "Prefer effortless scanning over maximum image visibility."]),
      section("luminance", "Control local luminance, not only average darkness", "Two dark images can behave very differently behind text. A smooth charcoal field creates predictable contrast, while a night city contains small white windows that interrupt character strokes. Evaluate local luminance where small text appears. Look for bright lines, sharp highlights, hard horizon edges, and alternating bands that cross the reading column. A temporary grayscale view helps because saturated blue or red can feel dark while still creating strong perceived edges. Reduce the brightest points, lift crushed shadows only when necessary, and compress tonal variation inside the reading zone. The focal region can retain more contrast on the right as long as responsive cropping does not pull it under core content.", ["Preview in grayscale.", "Inspect small muted metadata.", "Reduce isolated highlights behind text.", "Keep strong contrast inside the focal zone."]),
      section("texture", "Recognize texture that behaves like visual noise", "Fine texture competes with letterforms even when it is aesthetically subtle. Stars, rain, hair, foliage, circuitry, fabric, grain, and generated micro-details create thousands of edges. Blur can help, but blur applied after composition may produce glowing patches or halos that remain distracting. Start with simpler source structure: broad gradients, soft clouds, large geometric forms, or restrained depth. Zoom out to the size the image will actually occupy; details that look sophisticated at 100% may become flickering noise behind 13-pixel text. Also inspect compression artifacts around high-contrast edges. Export quality should preserve smooth gradients without creating blocks that resemble interface states.", ["Judge texture at final display size.", "Prefer large forms and slow gradients.", "Watch for blur halos and compression blocks.", "Remove generated detail from the reading field."]),
      section("states", "Test native states that a static mockup misses", "Interactive states reveal conflicts that a still image hides. Move keyboard focus through navigation, buttons, project cards, links, and composer controls. Select text, hover actionable elements, open menus, trigger a harmless validation message, and inspect disabled or secondary labels. Focus rings and selection colors must remain visible without looking like part of the wallpaper. The composer boundary should be obvious when empty, focused, and containing text. Check code syntax colors and inline links against both panels and exposed background. If you use more than one base appearance, repeat the test rather than assuming a palette that works in dark mode also works in a lighter state.", ["Check hover, focus, selected, and disabled states.", "Inspect code, links, warnings, and muted labels.", "Test the empty and focused composer.", "Repeat for every base appearance you use."]),
      section("responsive", "Repeat checks across window size and scaling", "Background cropping changes with width and height, while operating-system scaling changes the apparent density of text and controls. Test a wide window, a typical half-screen window, and the narrowest practical desktop width. On each size, visit home and task surfaces, then inspect the same focal points. A quiet left zone can disappear when a crop centers the image differently. A face safely on the right can move behind the reading column. The composer can cover more vertical space. Use the actual Windows scaling or macOS display mode you work with. Browser-style responsive previews are useful preparation, but the final decision belongs to the official app and the real visual workflow.", ["Test wide, medium, and narrow windows.", "Use your actual display scaling.", "Recheck both home and task surfaces.", "Do not approve from a design canvas alone."]),
      section("decision", "Use a publish-or-revise checklist", "Keep the theme only when the main reading column stays calm, muted text remains legible, focus is visible, the composer is distinct, and the focal art survives both crops. Revise when high-frequency detail crosses text, meaningful art sits under controls, or a palette depends on unusually opaque panels. Change one variable at a time: simplify detail, move the subject, reduce subject scale, compress luminance, or adjust accents. Record the export used so a good result can be reproduced. If you share the theme, include an honest preview from home and a populated task, state the intended base appearance, identify the image source, and avoid claiming compatibility beyond what you actually checked.", ["Pass: text remains effortless to scan.", "Pass: focus and composer boundaries stay clear.", "Revise: art competes with content or controls.", "Publish: show representative, rights-cleared evidence."]),
    ], related: ["background-image-composition", "image-rights-and-licensing", "codex-dream-skin-compatibility"],
  }),
  "image-rights-and-licensing": article({
    key: "image-rights-and-licensing", category: "guides", slug: "image-rights-and-licensing",
    seo: { title: "Image Rights and Licensing for Codex Themes", description: "Keep a practical rights record for photos, commissioned art, stock and generated backgrounds before using or sharing a Codex theme." },
    eyebrow: "Original publishing guide", h1: "Image Rights and Licensing for Codex Theme Backgrounds", summary: "Technical compatibility does not create permission: document where an image came from and what you may do with it before publishing a theme.",
    sections: [
      section("scope", "Separate personal use, display, and redistribution", "Using an image privately on your own desktop, showing a screenshot, and distributing the source image inside a downloadable theme are different acts. A license may allow one and restrict another. Start by writing down the planned use: personal customization, portfolio screenshot, free theme download, paid theme, client delivery, or social promotion. Then read the actual terms that apply to that use. Do not rely on a search-result label, a repost, or a file that lacks source information. This guide is a practical publishing checklist rather than legal advice; when ownership, commercial use, publicity rights, or local law is unclear, obtain permission or consult a qualified professional.", ["Define the exact planned use.", "Find the primary source and current terms.", "Treat screenshots and redistribution separately.", "Choose another asset when rights remain unclear."]),
      section("records", "Build a rights record at the moment you acquire the image", "Rights information is easiest to preserve when the file first enters your workflow. For your own photograph or illustration, keep the original file, creation date, and project notes. For commissioned work, retain the agreement and any written clarification about adaptation, display, sublicensing, and delivery to end users. For stock material, save the asset page, provider, contributor, license name and version, receipt, and download date. For public-domain or open-license material, save the source page and required attribution. Store this record next to the master image or in a small manifest so it does not disappear when filenames and folders change.", ["Creator or provider identity.", "Source URL and acquisition date.", "License version and proof of purchase.", "Attribution and redistribution conditions."]),
      section("generated", "Review generated images as outputs, not automatic ownership certificates", "A prompt and a generated file do not by themselves prove an unrestricted rights chain. Record the generator, account or workspace, date, prompt, model or service version when available, editing steps, and the provider terms that applied at creation. Inspect the result for logos, watermarks, recognizable characters, copied interface elements, celebrity likenesses, signatures, and accidental text. Regenerate or edit suspicious elements rather than assuming they are harmless because a model produced them. If a result closely imitates a named living artist, protected character, or recognizable campaign, choose a more independent direction. Keep the creation record with the final export and disclose the source method on a public theme page.", ["Save service, date, prompt, and applicable terms.", "Reject watermarks, signatures, logos, and characters.", "Avoid confusing imitation and official-looking branding.", "Disclose the source method honestly."]),
      section("people-brands", "Check portraits, trademarks, and implied affiliation", "Copyright is not the only concern. A recognizable person can raise consent, privacy, or publicity questions, especially in promotional or commercial contexts. A building, artwork, event badge, product design, or private location may carry its own restrictions. OpenAI and Codex names and marks should not be presented as your branding or as evidence of approval. Avoid placing official marks inside the background, naming a theme in a way that implies endorsement, or creating an official-looking download button. A factual description that the material is intended for a Codex customization workflow should sit beside a clear independent-site disclaimer and should never conceal the original tool source.", ["Get appropriate consent for recognizable people.", "Remove unneeded brands and protected characters.", "Avoid official-looking names, marks, and claims.", "Keep independent identity disclosure visible."]),
      section("license", "Choose explicit terms for work you are entitled to license", "If you created every relevant visual element and have the necessary rights, choose a clear license for the distributed asset. State whether personal and commercial use are allowed, whether modifications are permitted, whether the file may be redistributed alone or only as part of a theme, and whether attribution is required. Explain that the asset license does not cover OpenAI, Codex, third-party software, screenshots of official interfaces, or other excluded material. Do not apply an open license to an image that contains stock components whose terms prohibit sublicensing. A short, accurate custom notice is safer than attaching a familiar license name that you cannot actually grant.", ["State personal and commercial permissions.", "State modification and redistribution rules.", "Identify attribution requirements.", "List brands, software, and third-party exclusions."]),
      section("publish-check", "Use a final publish or do-not-publish decision", "Before uploading a background or theme page, verify that the rights record identifies a primary source, the planned distribution fits the terms, any attribution is present, and recognizable people or marks have been addressed. Preview files should not expose private task content or suggest official approval. The downloadable file should match the documented asset, without hidden extras or third-party installers. Publish the license next to the download and provide a contact route for corrections. Do not publish when the only source is a repost, terms cannot be recovered, a generated output contains suspicious protected elements, or you cannot explain whether recipients may keep and share the image.", ["Publish only with a complete source record.", "Match actual distribution to granted permissions.", "Place license and attribution beside the asset.", "Withhold uncertain files and replace them with original work."]),
    ], related: ["background-image-composition", "readability-and-contrast", "restore-default-appearance"],
  }),
  "theme-not-visible": article({
    key: "theme-not-visible", category: "troubleshooting", slug: "theme-not-visible",
    seo: { title: "Codex Dream Skin Theme Not Visible: Troubleshooting", description: "Diagnose a Codex theme that does not appear by separating source, launch, target, page, image, update and restore checks without bypassing security." },
    eyebrow: "Troubleshooting", h1: "Codex Dream Skin Theme Not Visible: A Reversible Diagnostic Path", summary: "Work from observable symptoms toward source, launch, target, compatibility, and verification evidence instead of repeating installation blindly.",
    sections: [
      section("symptom", "Describe exactly what is and is not visible", "Begin with the smallest factual description. Does official Codex open? Is the theme absent on both home and task views, visible only on home, visible only in one existing window, or replaced by a blank or partly styled layout? Did the helper report success, show an error, or close without readable output? Record the launcher or command used, the page open at the time, window size, and whether the problem began on first setup or after an update. Avoid the vague statement that it does not work. Different visible outcomes point to source, process, target selection, responsive styling, image preparation, or compatibility, and each category needs a different check.", ["Official app launch result.", "Home versus task behavior.", "Exact launcher and visible output.", "First install versus post-update failure."]),
      section("baseline", "Restore and establish an official-app baseline", "Use the documented restore path before deeper troubleshooting, then open Codex through its ordinary official entry point. Confirm that projects, authentication, navigation, tasks, and composer work without the third-party visual layer. If the official app is already broken, solve or report that baseline problem before changing theme files. A healthy baseline separates a styling failure from an app installation, account, or operating-system issue. Preserve logs and state until restore has run; deleting them first removes the helper’s record of its session. Once the baseline is clear, quit official Codex normally so the reviewed launcher can start from a known state.", ["Run documented restore before manual cleanup.", "Open official Codex independently.", "Verify normal tasks and controls.", "Quit cleanly before another launch attempt."]),
      section("source-launch", "Confirm source, version, and launch entry", "Return to the original repository rather than a copied archive or old blog attachment. Compare the checkout with the current platform README, review recent changes, and name the commit used. On Windows, verify the Store app and documented Node.js requirement. On macOS, verify processor architecture, official app location, and the exact .command or script entry. If a launcher closes immediately, run only its reviewed underlying script in a terminal to retain output. Do not compensate by disabling security, running unrelated binaries, or granting broad permissions. A provenance or prerequisite failure should be fixed at its source instead of being hidden by repeated administrator execution.", ["Use the original repository and current platform directory.", "Record the commit and prerequisite versions.", "Read terminal output from the reviewed script.", "Do not bypass warnings or broaden permissions casually."]),
      section("target", "Check that the intended Codex window is the target", "A local runtime styling workflow must connect to the expected official Codex renderer. Existing windows, stale helper state, multiple app instances, or another local debugging process can make target selection ambiguous. Close extra Codex windows and unrelated helper copies, then use the normal launcher’s documented behavior. If a local port is occupied, identify its owner rather than terminating arbitrary applications. Run the platform verify or doctor tool and keep its text output. A report that the app opened is not enough; evidence should show whether the expected endpoint and renderer were found and whether styling reached home and task surfaces.", ["Close duplicate windows and helper copies.", "Identify rather than guess about local ports.", "Use verify or doctor output.", "Check both renderer surfaces explicitly."]),
      section("image-style", "Separate image preparation from runtime styling", "If panels or accent colors change but the background does not, the runtime layer may be active while image preparation or configuration failed. Test with a rights-cleared, modest PNG or JPEG copy that meets documented platform limits. Avoid using a valuable original during diagnosis. Check whether the selected file was processed, where the project says the prepared asset belongs, and whether the applied theme references the current copy rather than an older path. If the background appears but text becomes unreadable, that is a composition problem, not proof that the helper failed. Use the composition and contrast guides after technical visibility is confirmed.", ["Use a simple licensed PNG or JPEG copy.", "Check documented format and size limits.", "Confirm the active theme references the intended asset.", "Treat readability separately from visibility."]),
      section("update-report", "Handle updates and submit useful evidence", "When a theme worked before an official Codex update, restore first, confirm the new official app works, then compare current upstream compatibility notes. Reinstall or reapply only as documented for the current source. Do not mix old installed files with newly downloaded launchers without reviewing migration behavior. If the issue remains, report operating system, processor architecture, official app distribution, source commit, exact launcher or command, sanitized verify output, and whether the problem affects home, task, or both. Remove usernames, tokens, private paths, project names, and task content. Documentation errors belong to CodexSkin; runtime behavior belongs to the upstream issue tracker.", ["Separate Codex and helper update timelines.", "Report exact environment and source state.", "Sanitize diagnostics before posting.", "Send the issue to the responsible project."]),
    ], related: ["cdp-port-conflict", "macos-permissions", "restore-default-appearance"],
  }),
  "cdp-port-conflict": article({
    key: "cdp-port-conflict", category: "troubleshooting", slug: "cdp-port-conflict",
    seo: { title: "Codex Dream Skin Local Port Conflict Guide", description: "Identify and resolve a local Codex Dream Skin CDP port conflict safely without terminating unrelated tools or exposing the endpoint." },
    eyebrow: "Troubleshooting", h1: "Diagnose a Codex Dream Skin Local CDP Port Conflict", summary: "Treat an occupied loopback port as an ownership and configuration question, not permission to kill unknown processes or expose debugging remotely.",
    sections: [
      section("meaning", "Understand what the port message means", "A local runtime styling helper can use a Chrome DevTools Protocol endpoint bound to the loopback interface so it can identify and style the expected Codex renderer. A message that a port is occupied means another process already owns that address and number, or a previous recorded session has not closed. It does not prove malware, and it does not prove the occupant is safe to terminate. Development servers, browsers, test tools, or another helper instance can all use local ports. Record the exact message, requested port, launcher arguments, and whether the normal launcher was allowed to choose automatically before taking action.", ["Copy the complete error text.", "Note automatic versus explicit port selection.", "Record whether Codex or a helper is already open.", "Do not infer process identity from the number alone."]),
      section("boundary", "Keep the debugging endpoint on loopback", "The reviewed upstream description uses a loopback-only connection. Preserve that boundary. Do not change the address to all interfaces, forward the port through a router, expose it through a tunnel, or disable local firewall protections to make styling work. CDP is powerful because it can inspect and control the connected renderer. Other untrusted local software can also be a concern while the endpoint is active. Run only software you trust during the session, restore when finished, and verify that the recorded endpoint closes. A conflict should be resolved locally through correct process ownership and configuration, never by making the endpoint reachable from the network.", ["Bind only to the documented loopback address.", "Do not tunnel or forward the endpoint.", "Avoid untrusted local software during the session.", "Restore and confirm closure afterward."]),
      section("identify", "Identify the owning process before changing anything", "Use the platform’s ordinary process and networking tools, or the project’s verify or doctor output, to identify which process is listening. Compare the process path, user account, start time, and parent process with applications you intentionally launched. Do not post the complete process list publicly because paths and arguments can contain personal information. If the owner is an unrelated development tool you need, close it normally or let the Dream Skin launcher choose a free port when that is its documented default. If the owner appears to be a stale recorded helper or themed Codex session, use the normal restore workflow rather than force-killing it first.", ["Verify process path, user, and start time.", "Close known tools through their normal exit path.", "Prefer documented automatic free-port selection.", "Use restore for recorded theme sessions."]),
      section("explicit", "Remove unnecessary explicit port overrides", "An explicit port is useful for controlled diagnosis but creates avoidable collisions in normal use. Review shortcuts, command history, environment configuration, or menu integrations for a manually supplied port. Remove the override only when the current upstream instructions say automatic selection is supported, then launch from a clean official-app state. Do not invent a random public-facing port or copy a number from another user’s issue. The helper and verification command must agree on the selected endpoint, so preserve diagnostic output that states which address was used. If an organization manages endpoint or firewall settings, follow that policy rather than bypassing it.", ["Inspect shortcuts and launcher arguments.", "Use automatic selection where documented.", "Keep launch and verify configuration consistent.", "Respect managed-device network policy."]),
      section("stale", "Distinguish stale state from an active conflict", "A sudden conflict after a crash can indicate that a process survived while its visible window closed, or that saved state refers to a session that no longer matches reality. Save work, run documented restore, wait for normal process shutdown, and confirm official Codex opens cleanly. Avoid deleting state until the restore attempt has used it. Relaunch once and note whether the conflict repeats on the same port. A one-time stale session and a reproducible collision with another application require different fixes. Repeated conflicts should include the owner identity, launch order, and configuration source in an upstream report, with private path and account information removed.", ["Restore before deleting state.", "Confirm official Codex after shutdown.", "Reproduce once from a clean state.", "Record owner and launch order if repeatable."]),
      section("success", "Define success and prepare a safe report", "The conflict is resolved when the normal launcher selects an available loopback endpoint, the intended renderer is verified, the theme works on required surfaces, and restore closes the recorded session. Success is not simply suppressing the error while an unknown listener remains. For an unresolved issue, include operating system, architecture, source commit, exact sanitized error, whether the port was automatic or explicit, the identified process category, and restore result. Do not publish tokens, command arguments containing secrets, personal paths, task screenshots, or full process inventories. CodexSkin can correct this guide; the upstream project must investigate tool behavior.", ["Available loopback endpoint selected.", "Expected renderer verified.", "Restore closes the recorded session.", "Sanitized, reproducible evidence ready if unresolved."]),
    ], related: ["theme-not-visible", "restore-default-appearance", "codex-dream-skin-compatibility"],
  }),
  "macos-permissions": article({
    key: "macos-permissions", category: "troubleshooting", slug: "macos-permissions",
    seo: { title: "Codex Dream Skin macOS Permissions Troubleshooting", description: "Distinguish Gatekeeper, executable permission, Finder, image access and architecture issues without globally weakening macOS security." },
    eyebrow: "Troubleshooting", h1: "Codex Dream Skin macOS Permissions: Diagnose the Exact Prompt", summary: "Resolve the narrow file or launch problem you can observe while preserving Gatekeeper, least privilege, and the signed official Codex app.",
    sections: [
      section("classify", "Classify the prompt before acting", "Not every macOS failure is the same permission problem. A file can lack its executable bit, carry a browser quarantine attribute, be blocked because its developer cannot be verified, fail because Finder and Terminal use different PATH values, request access to a selected image, or target an unsupported architecture. Copy the complete message and identify whether it comes from Finder, Terminal, System Settings, the shell, or the script itself. Note the exact .command file or script. Avoid broad advice such as allow everything; the safest solution depends on the precise layer that refused the action.", ["Capture the full message and source application.", "Name the exact launcher or script.", "Note Apple Silicon or Intel.", "Separate operating-system prompts from script errors."]),
      section("source", "Verify provenance before using Open Anyway", "A system-provided Open Anyway action does not verify that a download is safe. Return to the original repository, confirm owner and macOS directory, inspect the launcher and the script it calls, and review recent history. Compare any downloaded archive or files with the source method documented there. Do not follow a mirror that instructs you to disable Gatekeeper globally or paste an opaque command with elevated privileges. If the reviewed source does not explain why a permission is needed, stop. Keep the original Codex application in its normal signed location; the visual workflow should not require replacing or modifying it.", ["Use the verified original repository.", "Read launcher and called script together.", "Reject global security-disable instructions.", "Keep official Codex signed and unmodified."]),
      section("least-privilege", "Grant only narrow, explained access", "The customization flow may need the file you explicitly choose, and launchers need permission to execute. That does not imply a need for Full Disk Access, contacts, microphone, camera, broad accessibility control, or permanent administrator rights. When macOS offers a file-specific or application-specific decision, prefer it over weakening system-wide protection. Do not recursively make every downloaded file executable or remove quarantine from an entire home directory. If an organization manages your Mac, follow its policy and ask an administrator rather than bypassing controls. Record the narrow change you made so it can be reviewed or reversed later.", ["Prefer file-specific approval.", "Avoid unrelated privacy permissions.", "Do not modify whole directory trees.", "Follow managed-device policy."]),
      section("finder-terminal", "Compare Finder and Terminal behavior carefully", "A .command launcher opened from Finder can use a different working directory and environment from a shell in Terminal. If it closes immediately, run only the reviewed underlying script from its documented directory so output remains visible. A command-not-found result can be a PATH issue; a permission-denied result can be an executable or directory issue; a bad-CPU-type result points toward architecture. Do not treat all three by adding sudo. The upstream macOS workflow states that a separate global Node.js installation is not required, so an unexpected runtime download request should be investigated rather than accepted automatically.", ["Run the reviewed script from its documented directory.", "Read the exact shell error category.", "Do not use sudo as a universal fix.", "Check architecture and inherited PATH separately."]),
      section("image", "Separate selected-image access from launcher security", "If installation and launch succeed but image selection fails, test a copy of a modest, rights-cleared PNG or JPEG in a location you can normally read. This protects the original and helps isolate format, size, cloud-placeholder, and file-access behavior. Follow documented limits and avoid moving sensitive personal photos into public or shared folders merely to bypass a prompt. If Finder grants the selected file but processing fails, save the script output and check whether the prepared asset was created where the source documents expect it. Image failure does not justify broader application or disk access.", ["Use a non-sensitive test copy.", "Check format, size, and local availability.", "Keep private images out of public folders.", "Preserve sanitized processing output."]),
      section("recover", "Restore, verify, and report without weakening security", "After changing one narrow permission or correcting one source issue, relaunch from a clean state and run the documented Verify or doctor workflow. Check official Codex, home and task views, and image selection. Exercise Restore and confirm normal appearance returns. If the problem persists, report Mac model family, Apple Silicon or Intel, macOS version, source commit, exact launcher, complete sanitized error, and the narrow permissions already tried. Remove usernames, home paths, account details, and private image names. Do not report a workaround that disables system protection as a solution; report the underlying prompt and reproducible path instead. State whether the reviewed script behaves differently from Finder and Terminal, because that comparison separates inherited environment problems from file approval or architecture.", ["Verify after one change at a time.", "Confirm restore and official-app baseline.", "Report architecture and exact prompt.", "Keep security protections enabled."]),
    ], related: ["theme-not-visible", "restore-default-appearance", "image-rights-and-licensing"],
  }),
  "restore-default-appearance": article({
    key: "restore-default-appearance", category: "troubleshooting", slug: "restore-default-appearance",
    seo: { title: "Restore the Default Codex Appearance Safely", description: "Prepare, run, verify and troubleshoot the documented Windows or macOS Codex Dream Skin restore path without deleting diagnostic state first." },
    eyebrow: "Troubleshooting", h1: "Restore the Default Codex Appearance: Verification and Cleanup", summary: "Use the recorded platform restore first, verify a clean official launch, and separate recovery from optional removal of user-level theme files.",
    sections: [
      section("prepare", "Prepare before recovery", "Save work and note which Codex windows are open, which launcher began the session, and what remains styled. Close unrelated helper copies and terminals so the restore action has a clear target. Locate the source commit or installed files used during setup and compare current instructions before running a command. If the problem appeared after an update, record whether Codex, Windows or macOS, or the upstream project changed. Do not begin by deleting state, images, shortcuts, or logs. The recorded session and saved appearance values are evidence the documented restore process may need.", ["Save active work.", "Identify launcher and affected windows.", "Record source and update timeline.", "Preserve state until restore runs."]),
      section("platform", "Use the documented platform restore entry", "On Windows, use the Restore shortcut or the reviewed restore PowerShell script and understand whether optional flags restore appearance, remove shortcuts, or uninstall user-level helper files. On macOS, use Codex Dream Skin - Restore.command or the installed restore script described by the current source. Do not substitute a generic process killer or delete the official application. The intended restore targets the recorded helper and matching themed Codex session, returns saved appearance state where documented, and reopens official Codex. If the command differs from the source version you installed, stop instead of combining old state with guessed new arguments.", ["Choose the entry matching your platform and source.", "Read optional flags before using them.", "Do not remove or modify official Codex.", "Stop when source and installed version disagree."]),
      section("verify", "Verify a clean official launch twice", "Open Codex from its ordinary Start menu, Applications folder, Dock, or official shortcut rather than a theme launcher. Confirm custom background and accent treatment are absent on both home and task views. Verify projects, threads, authentication, provider settings, navigation, and composer remain available. Use verify or doctor output to confirm the recorded local styling session is no longer active. Then quit and open official Codex again. A result that survives a second clean launch is stronger evidence than one window that happened to lose its style while another helper remains active.", ["Use only the official app entry.", "Check home and task appearance.", "Confirm data and controls remain intact.", "Quit and repeat one clean launch."]),
      section("residual", "Interpret residual files and shortcuts correctly", "Restoration and uninstall are different goals. A clean official appearance can coexist with a user-selected image, log, state backup, or convenience shortcut left on disk. Those files do not prove that runtime styling is active. Identify each residual item from current upstream documentation before removing it. Keep sanitized logs until the restored state is stable. If you no longer want the helper, use a documented uninstall option where available and verify the scope before confirmation. Do not run broad cleanup commands copied from comments, and never delete official Codex data, authentication, projects, or configuration merely to remove a visual background.", ["Distinguish inactive files from active processes.", "Keep logs until recovery is confirmed.", "Use documented uninstall scope.", "Protect official app data and user projects."]),
      section("failure", "Diagnose a restore that appears to fail", "If the background remains, confirm that you did not reopen a theme shortcut. Close old windows and try the official entry. If only one window is styled, determine whether it predates restore. If official Codex is blank or broken without the helper, reproduce that baseline issue separately. When restore cannot identify recorded state, preserve output and compare installed files with the original commit. For a local-port message, identify the listener instead of terminating unrelated tools. Change one condition at a time and write down the order of restore, quit, and relaunch so the result can be reproduced.", ["Rule out the wrong shortcut.", "Separate old windows from new official launches.", "Reproduce official-app failures independently.", "Preserve ordered diagnostic steps."]),
      section("report", "Send evidence to the right maintainer", "CodexSkin can fix unclear wording, broken internal links, and composition guidance. It cannot diagnose or patch the third-party scripts. For upstream restore behavior, provide operating system, architecture, official app distribution, source commit, exact restore entry and flags, sanitized output, and the observed state after two official launches. Remove usernames, paths, tokens, account details, project names, task content, and private backgrounds. Explain facts separately from guesses and list every attempted action in order. A small reproducible report is more useful than many screenshots or a claim that reinstalling everything eventually worked. Keep original timestamped output locally until resolution, but publish only the minimum excerpt that shows the failing stage and preceding successful step. Note whether normal appearance persists after a reboot only when rebooting was actually part of your controlled test.", ["Route website issues to CodexSkin.", "Route script behavior to upstream.", "Sanitize logs and screenshots.", "Separate observations, actions, and hypotheses."]),
    ], related: ["theme-not-visible", "cdp-port-conflict", "macos-permissions"],
  }),
  "codex-dream-skin-compatibility": article({
    key: "codex-dream-skin-compatibility", category: "compatibility", slug: "codex-dream-skin",
    seo: { title: "Codex Dream Skin Compatibility: Windows and macOS", description: "Separate documented Windows and macOS requirements, CodexSkin observations, unknown states, update caveats, verification, and safe restore planning." },
    eyebrow: "Compatibility review", h1: "Codex Dream Skin Compatibility for Windows and macOS", summary: "Compatibility is a versioned claim: separate repository documentation, first-party observations, and unknown environments before deciding to run the visual helper.",
    sections: [
      section("meaning", "Treat compatibility as a dated, testable statement", "A screenshot or successful installation from months ago cannot prove that the current Codex app, operating system, and upstream source still work together. Compatibility involves the official app distribution, processor architecture, script prerequisites, renderer behavior, local endpoint selection, image processing, and recovery. This page was reviewed on 20 July 2026 and does not claim continuous testing after that date. Before use, compare the current original repository, its recent commits and issues, and the official app state on your machine. Preserve the source commit and environment details so your result can be repeated rather than described only as works for me.", ["Record review date and source commit.", "Name official app distribution.", "Include operating system and architecture.", "Retest after any relevant update."]),
      section("windows", "Documented Windows scope", "The reviewed upstream Windows guide targets the official Microsoft Store Codex app and lists Node.js 22 or newer with PowerShell. Its lifecycle includes installation, launch, verification, background selection through the current Windows tray experience, and restore. The project documentation describes package-identity checks and a local runtime styling connection rather than repackaging the signed Store application. These are attributed repository facts, not guarantees from OpenAI or CodexSkin. Windows editions, Store package changes, managed-device policy, security software, explicit local-port configuration, and future Codex renderer changes can still affect behavior.", ["Official Microsoft Store Codex app.", "Node.js 22 or newer and PowerShell.", "Separate install, start, verify, and restore stages.", "Recheck after Store or project updates."]),
      section("macos", "Documented macOS scope", "The reviewed macOS material addresses Apple Silicon and Intel Macs, expects the official Codex app to have been launched, and describes a local configuration under the user account. It says no separate global Node.js installation is required for that workflow. Finder .command launchers cover installation, launch, customization, verification, and restoration, with an optional menu integration. Documented image inputs include several common formats and size limits. Those facts remain source-dependent. Gatekeeper state, architecture, PATH differences between Finder and Terminal, file access, managed-device policy, and future official-app changes can produce environment-specific outcomes.", ["Apple Silicon and Intel are addressed.", "Official Codex should open first.", "No separate global Node.js is documented.", "Permission and architecture checks remain environment-specific."]),
      section("observed", "Separate CodexSkin practice notes from upstream facts", "CodexSkin’s first-party contribution is editorial organization, composition practice, readability checks, and independent review of public source documentation. The 20:9 canvas, right-side focal zone, left 55% quiet area, and bottom composer exclusion are practical findings for a shared home and task image; they are not platform requirements. CodexSkin does not distribute or alter the helper and does not claim to test every official Codex build. A theme that becomes visible is not automatically compatible: native navigation, task reading, composer use, focus states, verification output, and restore must also work in the user’s actual environment.", ["Composition percentages are practice guidance.", "Visibility alone is not compatibility.", "Native interaction and readability must remain intact.", "Restore is part of the compatibility test."]),
      section("unknown", "Label unknown or unverified environments honestly", "Do not infer support for Linux, unofficial Codex builds, repackaged desktop clients, remote debugging exposure, managed enterprise configurations, prerelease operating systems, or future processor architectures unless the current upstream project explicitly documents them. Absence from an issue tracker is not evidence of support. Likewise, one community comment cannot establish a general compatibility claim. For an unknown environment, read source, determine whether official app identity and platform entry points match, and stop if the workflow would require bypassing security or modifying the signed installation. Ask upstream maintainers before publishing a workaround as supported behavior.", ["Unknown does not mean unsupported or supported.", "Do not generalize from one report.", "Avoid unsigned mirrors and repackaged clients.", "Ask upstream before making broad claims."]),
      section("matrix", "Build a personal compatibility record", "Before relying on the theme, record operating system version, architecture, official Codex source, source commit, prerequisite versions, launcher, image format, and whether home, task, verify, and restore checks pass. After an update, restore first and confirm official Codex independently. Then compare the changed component and rerun the full record. If a failure remains, provide sanitized evidence to the responsible upstream tracker. Remove task content, usernames, tokens, personal paths, and private images. The useful outcome is not a permanent green badge; it is a dated matrix showing what you checked, what remains unknown, and how to return to the official appearance. Keep failed and successful records together so a later change can be associated with one component rather than vaguely attributed to the entire system. Mark skipped checks explicitly instead of letting an empty field look like a successful result.", ["Record environment and source precisely.", "Test home, task, verification, and restore.", "Repeat after updates.", "Keep unknown states visible instead of guessing."]),
    ], related: ["theme-not-visible", "readability-and-contrast", "restore-default-appearance"],
  }),
};
