import type { InfoPageContent } from "@/content/types";
import type { InfoRouteKey } from "@/lib/site";

export const enInfoContent: Record<InfoRouteKey, InfoPageContent> = {
  about: {
    seo: {
      title: "About CodexSkin – Independent Codex Themes & Guides",
      description: "Learn how CodexSkin creates independent Codex Desktop theme guidance, verifies third-party sources, and separates its work from OpenAI and upstream projects.",
    },
    eyebrow: "About this site",
    h1: "About CodexSkin",
    summary: "CodexSkin is an independent website for Codex Desktop theme inspiration, practical setup guidance, and original customization advice.",
    updatedLabel: "Last updated",
    updatedAt: "July 20, 2026",
    sections: [
      { id: "purpose", title: "What the site is for", paragraphs: ["CodexSkin helps visitors understand visual customization options for Codex Desktop, find the original source of referenced third-party projects, and follow platform-specific installation, customization, and restore guidance.", "The site also publishes original composition advice for background artwork. It does not provide a replacement Codex client, an automated installer, or a hosted copy of third-party packages."] },
      { id: "editorial", title: "How content is produced", paragraphs: ["Guides are written in original language after reviewing the linked upstream documentation. Platform requirements, script names, behavior claims, and safety boundaries are checked against the original repository before publication.", "Hands-on CodexSkin recommendations are labeled as tested guidance so they are not confused with OpenAI requirements or upstream-project guarantees."], items: ["Source links are centralized in the site configuration.", "Material changes receive a dated review.", "Unverified versions or capabilities are not presented as tested facts."] },
      { id: "independence", title: "Our relationship with OpenAI and upstream projects", paragraphs: ["CodexSkin.site is not owned, operated, endorsed, or sponsored by OpenAI. It is also not the official website of Codex Dream Skin, and the CodexSkin maintainer is not the upstream author.", "Third-party project names, trademarks, code, and assets remain the property of their respective owners and contributors. CodexSkin does not host, modify, or repackage third-party installers."] },
    ],
  },
  contact: {
    seo: {
      title: "Contact CodexSkin – Site Content & Corrections",
      description: "Find the correct channel for CodexSkin site corrections, content questions, and third-party Codex Dream Skin support without sending private information.",
    },
    eyebrow: "Contact",
    h1: "Contact CodexSkin",
    summary: "Contact CodexSkin by email for private site questions, use the public site repository for open corrections, and use the upstream repository for third-party tool support.",
    updatedLabel: "Last updated",
    updatedAt: "July 20, 2026",
    sections: [
      { id: "email", title: "Email CodexSkin", paragraphs: ["Use email for private website feedback, privacy questions, or messages that should not be posted in a public issue. Do not send passwords, API keys, authentication material, or unnecessary sensitive information."], links: [{ label: "weigensu@gmail.com", href: "mailto:weigensu@gmail.com" }] },
      { id: "site-feedback", title: "Public website corrections", paragraphs: ["Use the public CodexSkin site repository to report a broken link, translation problem, accessibility issue, or factual correction that can be discussed openly. Public issues must not contain private images or personal data."], items: ["Include the affected CodexSkin URL.", "Describe the expected and observed content.", "Link an authoritative source when proposing a factual correction."], links: [{ label: "Open the CodexSkin site repository", href: "https://github.com/swg209/codex-skin-site" }] },
      { id: "upstream-support", title: "Third-party tool support", paragraphs: ["Installation failures, runtime errors, compatibility reports, and feature requests for Codex Dream Skin belong in the original Fei-Away/Codex-Dream-Skin repository. CodexSkin does not develop or distribute that tool and cannot accept private support files on its behalf."] },
    ],
  },
  privacy: {
    seo: {
      title: "CodexSkin Privacy Policy – Analytics, Ads & Cookies",
      description: "Read how CodexSkin handles site access, Vercel Analytics, optional Google Analytics, Google AdSense, cookies, external links, and user-submitted data.",
    },
    eyebrow: "Policy",
    h1: "Privacy Policy",
    summary: "This policy describes the services actually present in the CodexSkin website and the data choices available to visitors.",
    updatedLabel: "Last updated",
    updatedAt: "July 20, 2026",
    sections: [
      { id: "scope", title: "Scope and contact", paragraphs: ["This policy covers CodexSkin.site and describes the services currently present on the website. Questions about this policy can be sent to the confirmed site contact address."], links: [{ label: "weigensu@gmail.com", href: "mailto:weigensu@gmail.com" }] },
      { id: "data", title: "Information you provide", paragraphs: ["CodexSkin has no account, login, payment, private support form, database-backed profile, or image-upload feature. If you email the published contact address, the email provider processes the address, message, headers, and attachments you choose to send so the message can be received and answered.", "Do not send passwords, API keys, authentication material, or information that is not necessary for the question. Information submitted after following an external link is handled by that external service under its own policy."] },
      { id: "hosting", title: "Hosting, request data, and security logs", paragraphs: ["Hosting and delivery providers may process technical request information such as IP address, browser and device type, requested URL, referrer, timestamps, and security logs as needed to deliver and protect the site.", "CodexSkin does not use this technical data to identify individual visitors. Providers may retain operational logs according to their own security and retention practices."] },
      { id: "vercel-analytics", title: "Vercel Analytics", paragraphs: ["The site uses Vercel Analytics to understand aggregate traffic and page performance. Those measurements help identify popular guides, broken journeys, and device-level layout problems without creating a CodexSkin account profile."] },
      { id: "google-analytics", title: "Conditional Google Analytics", paragraphs: ["Google Analytics is loaded only when a valid public measurement ID is configured. Its presence must not be assumed when that setting is absent. If enabled, the policy and consent configuration will be reviewed against the data actually collected before deployment."] },
      { id: "ads", title: "Google AdSense, third-party vendors, and cookies", paragraphs: ["CodexSkin uses Google AdSense. Third-party vendors, including Google, may place or read cookies on a visitor's browser, use web beacons, process IP addresses, or use similar identifiers when serving and measuring advertising on this website.", "Google and its advertising partners may use advertising cookies to select, limit, personalize, and measure advertisements. Depending on region, consent choice, and account settings, ads may use the current page, general location, or prior visits to CodexSkin and other websites.", "When a browser loads Google advertising services, it may send the page URL, IP address, browser and device information, timestamps, and advertising identifiers to Google for service delivery, measurement, fraud prevention, and permitted personalization."], links: [{ label: "How Google uses information from partner sites", href: "https://policies.google.com/technologies/partner-sites" }, { label: "How AdSense uses cookies", href: "https://support.google.com/adsense/answer/7549925" }] },
      { id: "ad-controls", title: "Personalized and non-personalized advertising", paragraphs: ["Advertising can be personalized or non-personalized according to the visitor's region, consent signal, browser controls, and Google settings. CodexSkin does not receive personal advertising profiles created by Google or other vendors and does not sell visitor-submitted personal information.", "Visitors can control personalized advertising through Google Ads Settings and can block or delete cookies through browser controls. Blocking advertising cookies may change ad behavior but does not prevent access to CodexSkin editorial content."], links: [{ label: "Google Ads Settings", href: "https://adssettings.google.com/" }] },
      { id: "regional-consent", title: "EEA, United Kingdom, and Switzerland consent", paragraphs: ["For visitors in the European Economic Area (EEA), the United Kingdom, and Switzerland, advertising consent must be collected through a Google-certified consent management platform where Google requires it. The available choices determine whether supported advertising storage and personalization purposes can be used.", "Visitors can change or withdraw a consent choice through the certified consent message when it is available. A general informational banner is not treated as a substitute for the certified consent process."] },
      { id: "retention", title: "Retention, security, and children", paragraphs: ["CodexSkin keeps no site database of visitor accounts or uploaded images. Email messages remain with the email provider only as long as reasonably needed to answer, document, or protect the correspondence. No internet service can promise absolute security, so visitors should minimize the information they send.", "The site is written for adults using developer desktop software and is not directed to children under 13. CodexSkin does not knowingly create child profiles or use children's activity for personalized advertising."] },
      { id: "external", title: "External links and policy updates", paragraphs: ["Links to GitHub, OpenAI-related resources, Google, and other websites leave CodexSkin and are governed by those services' own privacy practices.", "This policy will be revised when the site's actual analytics, advertising, contact, or data practices change. The date at the top identifies the current public revision."] },
    ],
  },
  terms: {
    seo: {
      title: "CodexSkin Terms of Use – Content & Third-Party Links",
      description: "Review the terms for using CodexSkin tutorials and original materials, following third-party links, respecting ownership, and understanding service limitations.",
    },
    eyebrow: "Policy",
    h1: "Terms of Use",
    summary: "These terms cover CodexSkin's independent editorial content and links to third-party software and services.",
    updatedLabel: "Last updated",
    updatedAt: "July 20, 2026",
    sections: [
      { id: "informational", title: "Informational use", paragraphs: ["CodexSkin provides tutorials, visual examples, and customization guidance for general informational purposes. You are responsible for deciding whether a third-party tool, script, image, or workflow is appropriate for your device, account, workplace, and local rules."] },
      { id: "materials", title: "Original and third-party materials", paragraphs: ["Original CodexSkin writing, page design, and clearly identified original materials may not be presented as your own work or used to impersonate CodexSkin. A separate license or notice controls any material that carries one.", "Third-party code, project names, screenshots, trademarks, and contributed artwork remain governed by their owners' licenses and rights. A software license does not automatically grant rights to portraits, trademarks, or every bundled image."] },
      { id: "links", title: "Third-party links and software", paragraphs: ["CodexSkin links to original repositories but does not control their availability, releases, security, or compatibility. Review source code, permissions, current documentation, and restore steps before running third-party scripts.", "Do not use CodexSkin content to imply official OpenAI support, upstream authorship, or a safety guarantee that the site has not made."] },
      { id: "availability", title: "No warranty and limitation of responsibility", paragraphs: ["The site and its editorial content are provided on an as-available basis without a promise of uninterrupted access, error-free instructions, permanent compatibility, or a particular result.", "To the extent permitted by applicable law, CodexSkin is not responsible for losses caused by third-party software, external services, user configuration, rights violations, or reliance on outdated information. Nothing here excludes rights or liability that cannot legally be excluded."] },
    ],
  },
  disclaimer: {
    seo: {
      title: "CodexSkin Disclaimer – Independent, Unofficial Guides",
      description: "Understand CodexSkin's independent status, third-party trademark and script risks, installer-hosting boundary, compatibility limits, and artwork responsibilities.",
    },
    eyebrow: "Disclosure",
    h1: "Disclaimer",
    summary: "CodexSkin is an independent editorial website, not an official OpenAI service or the official website of the projects it references.",
    updatedLabel: "Last updated",
    updatedAt: "July 20, 2026",
    sections: [
      { id: "identity", title: "Independent and unofficial", paragraphs: ["CodexSkin.site is not affiliated with, endorsed by, sponsored by, or operated by OpenAI. It is not the official Codex Dream Skin website, and its maintainer is not the developer of that upstream project.", "OpenAI, Codex, project names, company names, and other marks belong to their respective owners. Reference to them is descriptive and does not imply partnership or endorsement."] },
      { id: "software", title: "Third-party scripts and installers", paragraphs: ["CodexSkin does not host, modify, proxy, automatically download, or repackage Codex Dream Skin installers. Links direct visitors to an original third-party repository verified on the date stated on the project guide.", "Running a local debugging or runtime styling helper can carry security and compatibility risk. Review the source, understand requested permissions, keep restore instructions available, and do not treat any guide as a guarantee of absolute safety.", "The referenced tool connects to a user-launched local Codex session through a loopback-only Chrome DevTools Protocol endpoint and applies visual CSS at runtime. CodexSkin provides no method for bypassing access controls, licensing, signatures, or security protections."] },
      { id: "accuracy", title: "Accuracy and compatibility", paragraphs: ["Documentation and software can change after publication. Codex updates may require a third-party theme to be reinstalled, adapted, or temporarily discontinued. CodexSkin does not promise permanent compatibility or continuous availability."] },
      { id: "artwork", title: "Artwork and user responsibility", paragraphs: ["Theme examples can contain user-provided, AI-generated, trademarked, or likeness-related material. Before using or redistributing an image, confirm that you have the necessary rights and that the intended use complies with applicable rules."] },
    ],
  },
};

export const zhInfoContent: Record<InfoRouteKey, InfoPageContent> = {
  about: {
    seo: { title: "关于 CodexSkin - 独立 Codex 主题与教程网站", description: "了解 CodexSkin 如何制作独立的 Codex 桌面端主题教程、核对第三方来源，并明确本站与 OpenAI 及上游项目的关系。" },
    eyebrow: "关于本站",
    h1: "关于 CodexSkin",
    summary: "CodexSkin 是提供 Codex 桌面端主题灵感、实用教程与原创定制建议的独立网站。",
    updatedLabel: "最后更新",
    updatedAt: "2026年7月20日",
    sections: [
      { id: "purpose", title: "网站用途", paragraphs: ["CodexSkin 帮助访问者了解 Codex 桌面端的视觉定制方式、找到所引用第三方项目的原始来源，并阅读分平台安装、定制和恢复教程。", "本站也发布原创背景图构图经验，但不提供替代版 Codex 客户端、自动安装服务或第三方安装包镜像。"] },
      { id: "editorial", title: "内容如何制作与核对", paragraphs: ["教程使用原创表述，并在发布前检查所链接的上游文档。平台要求、脚本名称、行为说明和安全边界均以原始仓库为主要核对依据。", "CodexSkin 自己的实践经验会明确标注为实测建议，避免被误解为 OpenAI 要求或上游项目保证。"], items: ["上游链接集中在站点配置中维护。", "重要变化会记录核对日期。", "未核验的版本或能力不会写成本站实测事实。"] },
      { id: "independence", title: "与 OpenAI 和上游项目的关系", paragraphs: ["CodexSkin.site 不属于 OpenAI，也未获得 OpenAI 运营、认可、赞助或背书。本站也不是 Codex Dream Skin 官方网站，本站维护者不是其上游作者。", "第三方项目名称、商标、代码和素材归对应权利人及贡献者所有。本站不托管、不修改、不重新打包第三方安装程序。"] },
    ],
  },
  contact: {
    seo: { title: "联系 CodexSkin - 网站内容反馈与纠错", description: "了解 CodexSkin 网站纠错、内容问题与第三方 Codex Dream Skin 支持应使用的渠道，并避免提交隐私或敏感信息。" },
    eyebrow: "联系",
    h1: "联系 CodexSkin",
    summary: "私密网站问题可通过邮箱联系，公开纠错可使用网站源码仓库，第三方工具问题则应提交到上游项目。",
    updatedLabel: "最后更新",
    updatedAt: "2026年7月20日",
    sections: [
      { id: "email", title: "通过邮箱联系 CodexSkin", paragraphs: ["私密网站反馈、隐私问题或不适合公开发布的信息可以发送到联系邮箱。不要发送密码、API Key、身份验证材料或与问题无关的敏感信息。"], links: [{ label: "weigensu@gmail.com", href: "mailto:weigensu@gmail.com" }] },
      { id: "site-feedback", title: "公开网站纠错", paragraphs: ["失效链接、翻译、无障碍问题或事实错误如可公开讨论，请使用 CodexSkin 网站源码仓库。公开 Issue 不得包含私人图片或个人数据。"], items: ["附上受影响的 CodexSkin 页面 URL。", "说明预期内容和当前表现。", "事实纠错尽量提供权威来源链接。"], links: [{ label: "打开 CodexSkin 网站源码仓库", href: "https://github.com/swg209/codex-skin-site" }] },
      { id: "upstream-support", title: "第三方工具支持", paragraphs: ["Codex Dream Skin 的安装失败、运行错误、兼容性报告和功能建议，应提交到原始 Fei-Away/Codex-Dream-Skin 仓库。CodexSkin 不开发或分发该工具，也不代表上游接收私人支持文件。"] },
    ],
  },
  privacy: {
    seo: { title: "CodexSkin 隐私政策 - 统计、广告与 Cookie", description: "了解 CodexSkin 如何处理网站访问、Vercel Analytics、可选 Google Analytics、Google AdSense、Cookie、外部链接与用户提交数据。" },
    eyebrow: "政策",
    h1: "隐私政策",
    summary: "本政策仅说明 CodexSkin 网站实际存在的服务，以及访问者可以使用的数据和 Cookie 控制方式。",
    updatedLabel: "最后更新",
    updatedAt: "2026年7月20日",
    sections: [
      { id: "scope", title: "适用范围与联系方式", paragraphs: ["本政策适用于 CodexSkin.site，并说明网站当前实际使用的服务。与本政策有关的问题可以发送到已经确认的联系邮箱。"], links: [{ label: "weigensu@gmail.com", href: "mailto:weigensu@gmail.com" }] },
      { id: "data", title: "你主动提供的信息", paragraphs: ["CodexSkin 没有账号、登录、支付、私密支持表单、数据库个人资料或图片上传功能。如果你向公开邮箱发信，邮件服务商会为接收和回复邮件而处理你选择发送的邮箱地址、正文、邮件头和附件。", "请勿发送密码、API Key、身份验证材料或与问题无关的信息。访问外部链接后提交的信息由对应外部服务按照其政策处理。"] },
      { id: "hosting", title: "托管、请求数据与安全日志", paragraphs: ["托管和内容分发服务可能为交付及保护网站处理必要的技术请求信息，例如 IP 地址、浏览器和设备类型、访问 URL、来源页、时间戳及安全日志。", "CodexSkin 不使用这些技术信息主动识别单个访问者；服务商可能按照自身安全和留存规则保存运行日志。"] },
      { id: "vercel-analytics", title: "Vercel Analytics", paragraphs: ["本站使用 Vercel Analytics 了解汇总流量和页面表现，用于发现受欢迎的教程、失效的访问路径和设备端布局问题，不会因此创建 CodexSkin 账号画像。"] },
      { id: "google-analytics", title: "按配置启用的 Google Analytics", paragraphs: ["只有配置有效的公开 Measurement ID 时才会加载 Google Analytics；没有该配置时不应视为已启用。如未来启用，部署前会根据真实收集的数据重新核对本政策和同意设置。"] },
      { id: "ads", title: "Google AdSense、第三方供应商与 Cookie", paragraphs: ["CodexSkin 使用 Google AdSense。Google 等第三方供应商在本站投放和衡量广告时，可能在浏览器中放置或读取 Cookie、使用网络信标、处理 IP 地址或使用其他类似标识符。", "Google 及其广告合作方可能使用广告 Cookie 选择、限制、个性化及衡量广告。根据地区、同意选择和账号设置，广告可能参考当前页面、一般位置，以及此前对 CodexSkin 或其他网站的访问。", "浏览器加载 Google 广告服务时，可能向 Google 发送页面 URL、IP 地址、浏览器和设备信息、时间戳及广告标识符，用于提供服务、衡量效果、防止欺诈及在允许时提供个性化体验。"], links: [{ label: "Google 如何使用合作伙伴网站的信息", href: "https://policies.google.com/technologies/partner-sites" }, { label: "AdSense 如何使用 Cookie", href: "https://support.google.com/adsense/answer/7549925" }] },
      { id: "ad-controls", title: "个性化与非个性化广告", paragraphs: ["广告可能根据访问者地区、同意信号、浏览器控制和 Google 设置采用个性化或非个性化方式。CodexSkin 不会获得 Google 或其他供应商创建的个人广告画像，也不会出售访问者主动提交的个人信息。", "访问者可以通过 Google 广告设置控制个性化广告，也可以通过浏览器阻止或删除 Cookie。阻止广告 Cookie 可能改变广告行为，但不会阻止阅读 CodexSkin 正文。"], links: [{ label: "Google 广告设置", href: "https://adssettings.google.com/" }] },
      { id: "regional-consent", title: "欧洲经济区、英国与瑞士的同意要求", paragraphs: ["对于欧洲经济区（EEA）、英国和瑞士访问者，在 Google 要求的情况下，广告同意将通过 Google 认证的同意管理平台收集。可用选择会决定是否允许相关广告存储和个性化目的。", "访问者可通过认证同意消息更改或撤回选择。普通信息提示条不会被当作认证同意流程的替代品。"] },
      { id: "retention", title: "留存、安全与儿童", paragraphs: ["CodexSkin 不保存访客账号或上传图片的站点数据库。邮件只会在合理回复、记录或保护通信所需时间内保留在邮件服务商中。任何互联网服务都无法承诺绝对安全，因此请尽量减少发送的信息。", "本站面向使用开发者桌面软件的成年人，不以 13 岁以下儿童为目标，也不会主动创建儿童画像或利用儿童活动进行个性化广告。"] },
      { id: "external", title: "外部链接与政策更新", paragraphs: ["访问 GitHub、OpenAI 相关资源、Google 或其他外部网站后，将适用对应服务自己的隐私规则。", "当网站真实使用的统计、广告、联系或数据流程变化时，本政策会同步更新；页面顶部日期代表当前公开版本。"] },
    ],
  },
  terms: {
    seo: { title: "CodexSkin 使用条款 - 内容与第三方链接", description: "查看 CodexSkin 教程和原创素材的使用条件、第三方链接与软件责任、权利归属、禁止冒充以及服务限制。" },
    eyebrow: "政策",
    h1: "使用条款",
    summary: "这些条款适用于 CodexSkin 的独立编辑内容，以及本站指向第三方软件和服务的链接。",
    updatedLabel: "最后更新",
    updatedAt: "2026年7月20日",
    sections: [
      { id: "informational", title: "信息用途", paragraphs: ["CodexSkin 提供的教程、视觉示例和定制建议仅用于一般信息参考。你需要自行判断第三方工具、脚本、图片或操作流程是否适合自己的设备、账号、工作环境和当地规则。"] },
      { id: "materials", title: "原创与第三方素材", paragraphs: ["CodexSkin 原创文字、页面设计和明确标注的原创素材，不得被冒充为他人原创或用于假冒 CodexSkin。带有单独许可或声明的素材，以对应文件为准。", "第三方代码、项目名称、截图、商标和贡献素材仍受各自权利人许可与权利约束。软件许可证不当然授予人物肖像、商标或全部随附图片的使用权。"] },
      { id: "links", title: "第三方链接与软件", paragraphs: ["CodexSkin 链接到原始仓库，但不控制其可用性、版本、安全性或兼容性。运行第三方脚本前，请检查源码、权限、最新文档和恢复方法。", "不得利用本站内容暗示 OpenAI 官方支持、冒充上游作者，或宣称本站未作出的安全保证。"] },
      { id: "availability", title: "无保证与责任限制", paragraphs: ["本站及编辑内容按现状和可用状态提供，不承诺持续无中断、教程绝无错误、永久兼容或一定达到某种效果。", "在适用法律允许范围内，CodexSkin 不对第三方软件、外部服务、用户配置、权利侵害或依赖过期信息造成的损失负责；法律不得排除的权利或责任不受本条影响。"] },
    ],
  },
  disclaimer: {
    seo: { title: "CodexSkin 免责声明 - 独立非官方教程", description: "了解 CodexSkin 的独立身份、第三方商标与脚本风险、不托管安装程序的边界、兼容性限制及图片素材责任。" },
    eyebrow: "声明",
    h1: "免责声明",
    summary: "CodexSkin 是独立编辑网站，不是 OpenAI 官方服务，也不是所引用项目的官方网站。",
    updatedLabel: "最后更新",
    updatedAt: "2026年7月20日",
    sections: [
      { id: "identity", title: "独立且非官方", paragraphs: ["CodexSkin.site 与 OpenAI 没有隶属、认可、赞助或运营关系。本站不是 Codex Dream Skin 官方网站，本站维护者也不是该上游项目开发者。", "OpenAI、Codex、项目名、公司名及其他商标归各自权利人所有。本站仅为说明性引用，不代表合作或背书。"] },
      { id: "software", title: "第三方脚本与安装程序", paragraphs: ["CodexSkin 不托管、不修改、不代理、不自动下载、不重新打包 Codex Dream Skin 安装程序。页面链接指向项目页所列核对日期确认的第三方原始仓库。", "运行本机调试或运行时样式辅助程序可能存在安全和兼容风险。请检查源码、理解权限、保留恢复步骤，不要把任何教程理解为绝对安全保证。", "所引用工具通过仅限本机回环地址的 Chrome DevTools Protocol 连接用户主动启动的 Codex 会话，并在运行时应用视觉 CSS。CodexSkin 不提供绕过访问控制、许可、签名或安全保护的方法。"] },
      { id: "accuracy", title: "准确性与兼容性", paragraphs: ["文档和软件可能在本站发布后变化。Codex 更新可能导致第三方主题需要重装、适配或暂时停止使用；CodexSkin 不承诺永久兼容或持续可用。"] },
      { id: "artwork", title: "图片素材与用户责任", paragraphs: ["主题示例可能包含用户提供、AI 生成、商标或人物相关素材。使用或再次分发图片前，请确认拥有必要权利，并确保用途符合适用规则。"] },
    ],
  },
};
