import type { LocaleContent } from "@/content/types";

const nav = {
  themes: "主题效果",
  features: "功能",
  install: "安装",
  faq: "常见问题",
  github: "GitHub",
  menu: "打开菜单",
  closeMenu: "关闭菜单",
};

export const zhContent: LocaleContent = {
  locale: "zh",
  chrome: {
    nav,
    localeLabel: "English",
    skipLabel: "跳到正文",
    footerDescription: "为官方 Codex 桌面端添加可恢复的开源主题层。",
    repositoryLabel: "GitHub 仓库",
    guidesLabel: "安装教程",
    issueLabel: "反馈问题",
    licenseLabel: "MIT 许可",
    privacyTitle: "隐私",
    privacyText: "本站为静态网站，没有账号、表单或上传功能。只有站长启用后才会加载匿名统计。",
    disclaimer: "Codex Dream Skin 是独立开源项目，与 OpenAI 没有隶属、认可或赞助关系。Codex 及 OpenAI 相关商标归其权利人所有。",
  },
  home: {
    seo: {
      title: "Codex Dream Skin - Codex 桌面端主题与换肤工具",
      description: "为 Codex 桌面端添加自定义主题和背景图片，支持 Windows 与 macOS，不修改官方安装包，并可恢复官方外观。",
    },
    nav,
    hero: {
      eyebrow: "开源 Codex 桌面端主题工具",
      h1: "给 Codex 桌面端换一张会呼吸的脸",
      description: "通过主题与背景打造更有氛围的 Codex 工作空间，支持 Windows 与 macOS，不修改官方安装包。",
      proofLabels: ["Windows", "macOS", "开源项目", "一键恢复"],
    },
    galleryTitle: "八种氛围，仍是熟悉的工作区",
    galleryIntro: "这些仓库内的合成效果图展示了 Dream Skin 如何改变主页和任务页，同时保留 Codex 原生交互。",
    galleryDisclaimer: "主题图片仅用于演示。用户有责任确保其选择的图片拥有使用和再分发权利。",
    gallery: [
      { name: "粉色空间", description: "柔和粉色背景与半透明内容层组成的 Codex 工作区。", src: "/themes/skin-01.jpg" },
      { name: "金色工作台", description: "以暖金色氛围衬托原生项目控件。", src: "/themes/skin-02.jpg" },
      { name: "红白未来", description: "清晰利落的红白科幻 Codex 桌面主题。", src: "/themes/skin-03.jpg" },
      { name: "清透日光", description: "明亮、低干扰的清透工作空间。", src: "/themes/skin-04.jpg" },
      { name: "灵感宇宙", description: "位于原生 Codex 界面之后的深空构图。", src: "/themes/skin-05.jpg" },
      { name: "紫夜限定", description: "兼顾任务文字可读性的克制紫夜主题。", src: "/themes/skin-06.jpg" },
      { name: "虚拟舞台", description: "作为主题示例展示的明快虚拟舞台构图。", src: "/themes/skin-07.jpg" },
      { name: "黑金舞台", description: "富有戏剧感的黑金 Codex 工作空间。", src: "/themes/skin-08.jpg" },
    ],
    featuresTitle: "是主题层，不是假界面",
    featuresIntro: "Dream Skin 改变官方应用周围的氛围，但不会拿一张截图替代你正在使用的控件。",
    features: [
      { title: "真实可交互界面", description: "侧栏、建议卡、项目选择、任务内容、菜单和输入框仍然是 Codex 原生控件。" },
      { title: "macOS 支持自己的图片", description: "macOS 主题编辑器可以处理本地图片，并生成主页横幅和任务背景。" },
      { title: "支持 Windows 与 macOS", description: "仓库按平台提供安装、启动、验证和恢复流程。" },
      { title: "不修改官方应用", description: "不会修改 .app、app.asar、WindowsApps 或官方代码签名。" },
      { title: "一键恢复", description: "平台启动器和脚本可以停止主题会话，并重新打开官方外观。" },
      { title: "本机 CDP 注入", description: "主题通过仅绑定回环地址的调试端点注入预期的 Codex 渲染页面。" },
    ],
    stepsTitle: "从仓库到新外观",
    steps: [
      { title: "1. 安装 Dream Skin", description: "打开对应平台教程，使用仓库中真实存在的安装入口。" },
      { title: "2. 应用可用主题", description: "使用平台启动器；macOS 还可以处理自己准备的受支持图片。" },
      { title: "3. 启动 Codex", description: "Dream Skin 通过本机主题会话启动官方应用，原有控件仍可正常使用。" },
    ],
    proofTitle: "围绕你熟悉的 Codex 设计",
    proofDescription: "视觉层位于原生导航、建议卡、项目控件、任务内容和输入框之后，不会用整窗假截图替代它们。",
    safetyTitle: "清楚说明安全边界",
    safetyIntro: "CDP 本身能力很强。Dream Skin 将其限制在本机 Codex 目标上，但主题运行期间仍应把它视为敏感的本机调试会话。",
    safety: [
      "CDP 监听地址仅绑定本机回环。",
      "不修改官方 .app、app.asar、WindowsApps 包或代码签名。",
      "不会自动改写 API Key、Base URL 或模型供应商设置。",
      "主题会话运行时不要启动来源不明的本机程序。",
      "Codex 更新后可能需要重新应用或等待兼容更新。",
      "这是独立项目，不是 OpenAI 官方产品。",
    ],
    faqTitle: "常见问题",
    faq: [
      { question: "Codex Dream Skin 是什么？", answer: "它是一个开源主题层，通过本机 CDP 向官方 Codex 桌面端注入 CSS 和装饰界面元素。" },
      { question: "这是 OpenAI 官方产品吗？", answer: "不是。它是独立开源项目，与 OpenAI 没有隶属或认可关系。" },
      { question: "它会修改 Codex 安装包吗？", answer: "不会。项目不修改官方 .app、app.asar、WindowsApps 包或代码签名。" },
      { question: "支持 Windows 吗？", answer: "支持。仓库提供面向微软商店版 Codex 的 Windows 安装、启动、验证和恢复脚本。" },
      { question: "支持 Apple Silicon 和 Intel Mac 吗？", answer: "支持。macOS 流程会验证官方 Codex 应用，并兼容 Apple Silicon 与 Intel Mac。" },
      { question: "可以使用自己的背景图吗？", answer: "仓库记录的 macOS 编辑器支持 PNG、JPEG、HEIC、TIFF 和 WebP。本版 Windows 流程没有同样的图片选择器。" },
      { question: "如何恢复官方外观？", answer: "使用对应平台的 Restore 启动器或恢复脚本，它会停止记录的主题会话并重新打开官方应用。" },
      { question: "Codex 更新后还能继续用吗？", answer: "不保证完全无需处理。应用更新可能改变渲染结构，届时需要重装、重新应用或等待兼容更新。" },
      { question: "它会改 API 配置吗？", answer: "不会自动修改 API Key、Base URL 或模型供应商。主题配置与 API 供应商配置彼此独立。" },
      { question: "在哪里反馈问题？", answer: "请使用 swg209/Codex-Dream-Skin GitHub 仓库的 Issue 模板，并附上平台和验证结果。" },
    ],
    finalTitle: "给 Codex 换一个新外观",
    finalDescription: "选择你的平台，阅读经过核对的步骤，并把 Restore 恢复入口留在手边。",
    labels: {
      windows: "Windows 安装",
      macos: "macOS 安装",
      github: "查看 GitHub",
      previous: "上一个主题",
      next: "下一个主题",
      close: "关闭预览",
      viewTheme: "查看主题",
    },
  },
  guides: {
    windows: {
      key: "windows",
      seo: { title: "Windows 安装 Codex Dream Skin", description: "为 Windows 官方 Codex 桌面端安装、启动、验证并恢复 Codex Dream Skin。" },
      eyebrow: "Windows 安装",
      h1: "在 Windows 安装 Codex Dream Skin",
      summary: "使用仓库中的 PowerShell 流程为微软商店版 Codex 添加主题，不修改 WindowsApps。",
      sourceLabel: "打开 Windows 源码",
      issueLabel: "反馈 Windows 问题",
      copyLabel: "复制",
      copiedLabel: "已复制",
      copyFailedLabel: "请手动选择并复制命令",
      contentsLabel: "本页内容",
      relatedLabel: "相关教程",
      sections: [
        { id: "support", title: "支持与要求", blocks: [{ type: "list", items: ["已安装微软商店官方 Codex 的 Windows", "Node.js 22 或更高版本", "PowerShell", "允许创建桌面和开始菜单快捷方式"] }] },
        { id: "prepare", title: "安装前准备", tone: "warning", blocks: [{ type: "paragraph", text: "安装前关闭 Codex。安装器会验证已注册的商店应用身份，无法验证官方包时会停止。" }, { type: "paragraph", text: "下载或克隆 GitHub 仓库，并在 windows 目录打开 PowerShell。核对本教程时仓库尚未发布 Release 安装包。" }] },
        { id: "install", title: "安装启动器", blocks: [{ type: "code", language: "powershell", code: ".\\scripts\\install-dream-skin.ps1" }, { type: "paragraph", text: "安装器会记录现有外观值、设置配套基础主题，并在未使用 -NoShortcuts 时创建启动和恢复快捷方式。" }] },
        { id: "launch", title: "启动主题会话", blocks: [{ type: "code", language: "powershell", code: ".\\scripts\\start-dream-skin.ps1" }, { type: "paragraph", text: "如果 Codex 已经打开但没有经过验证的 Dream Skin 端点，请先关闭它。命令行调用者只有明确添加 -RestartExisting 才会重启已打开窗口。" }] },
        { id: "verify", title: "验证主题", blocks: [{ type: "code", language: "powershell", code: ".\\scripts\\verify-dream-skin.ps1 -ScreenshotPath \"$env:USERPROFILE\\Desktop\\codex-dream-skin.png\"" }, { type: "paragraph", text: "同时检查主页和普通任务页。缺少横幅、原生输入框、侧栏主题或注入标记都属于验证失败。" }] },
        { id: "change", title: "Windows 主题变更", tone: "note", blocks: [{ type: "paragraph", text: "当前 Windows 包使用随仓库提供的装饰资源，没有记录 macOS 的图片选择器流程。请优先查看仓库更新记录，不要直接套用第三方教程。" }] },
        { id: "restore", title: "恢复官方外观", blocks: [{ type: "code", language: "powershell", code: ".\\scripts\\restore-dream-skin.ps1 -RestoreBaseTheme" }, { type: "paragraph", text: "恢复流程会关闭记录的 CDP 会话、还原保存的外观项并重新打开官方应用。只有同时想移除快捷方式时才添加 -Uninstall。" }] },
        { id: "troubleshooting", title: "常见问题", blocks: [{ type: "list", items: ["默认 9335 端口被占用时，普通启动器会选择空闲端口；明确指定了被占用端口则会停止。", "Codex 更新后重新运行安装和启动，让脚本重新发现当前商店包。", "本机 CDP 会话运行时不要启动不可信软件。", "主题没有出现时，通过 GitHub Issue 提交 verify 输出。"] }] },
      ],
      related: ["macos", "restore", "customize"],
    },
    macos: {
      key: "macos",
      seo: { title: "macOS 安装 Codex Dream Skin", description: "在 Apple Silicon 或 Intel Mac 安装 Codex Dream Skin，选择背景、验证效果并恢复 Codex。" },
      eyebrow: "macOS 安装",
      h1: "在 macOS 安装 Codex Dream Skin",
      summary: "在 Apple Silicon 或 Intel Mac 为官方 Codex 桌面端安装主题编辑器，并通过 Finder 启动器定制、验证和恢复。",
      sourceLabel: "打开 macOS 源码",
      issueLabel: "反馈 macOS 问题",
      copyLabel: "复制",
      copiedLabel: "已复制",
      copyFailedLabel: "请手动选择并复制命令",
      contentsLabel: "本页内容",
      relatedLabel: "相关教程",
      sections: [
        { id: "support", title: "支持与要求", blocks: [{ type: "list", items: ["Apple Silicon 或 Intel Mac", "已安装并至少启动过一次官方 Codex 桌面端", "本机存在 ~/.codex/config.toml", "不需要另外安装全局 Node.js"] }] },
        { id: "download", title: "获取安装器", blocks: [{ type: "paragraph", text: "打开仓库的 macos 目录。核对本教程时尚未发布 GitHub Release，请使用仓库文件，不要使用来历不明的下载镜像。" }] },
        { id: "install", title: "安装 Dream Skin", blocks: [{ type: "paragraph", text: "在 Finder 双击 Install Codex Dream Skin.command。下面的源码命令可以只安装而不立即启动。" }, { type: "code", language: "bash", code: "./scripts/install-dream-skin-macos.sh --no-launch" }] },
        { id: "launch", title: "启动与定制", blocks: [{ type: "paragraph", text: "使用 Start Codex Dream Skin.command 启动或重新应用主题；使用 Customize Codex Dream Skin.command 通过 Finder 选择图片。" }, { type: "code", language: "bash", code: "~/.codex/codex-dream-skin-studio/scripts/customize-theme-macos.sh" }] },
        { id: "verify", title: "验证结果", blocks: [{ type: "paragraph", text: "双击 Verify Codex Dream Skin.command，并检查主页和普通任务页，确认原生侧栏、项目选择、输入框和任务内容仍可使用。" }, { type: "code", language: "bash", code: "~/.codex/codex-dream-skin-studio/scripts/doctor-macos.sh" }] },
        { id: "image", title: "背景图片建议", blocks: [{ type: "list", items: ["支持 PNG、JPEG、HEIC、TIFF 和 WebP", "源文件不超过 50 MB", "处理后文件不超过 16 MB", "建议使用宽度至少 2000px 的横图", "左侧尽量简洁，为原生主页标题留出空间"] }] },
        { id: "restore", title: "恢复 Codex", blocks: [{ type: "paragraph", text: "双击 Restore Codex Dream Skin.command。恢复流程只停止记录的注入器和匹配的主题 Codex 会话，然后重新打开官方应用。" }, { type: "code", language: "bash", code: "./scripts/restore-dream-skin-macos.sh" }] },
        { id: "menu", title: "可选菜单栏", blocks: [{ type: "paragraph", text: "使用 SwiftBar 时可以安装菜单栏命令，用于应用、暂停和更换图片。" }, { type: "code", language: "bash", code: "./Install\\ Menu\\ Bar.command" }] },
      ],
      related: ["customize", "restore", "windows"],
    },
    customize: {
      key: "customize",
      seo: { title: "定制 Codex Dream Skin 主题", description: "准备清晰易读的背景图片，并使用 macOS 主题编辑器定制 Codex Dream Skin。" },
      eyebrow: "主题教程",
      h1: "定制你的 Codex Dream Skin 主题",
      summary: "准备一张横向图片，保证原生文字可读，再用仓库记录的 macOS 编辑器生成主题资源。",
      sourceLabel: "打开定制源码",
      issueLabel: "反馈定制问题",
      copyLabel: "复制",
      copiedLabel: "已复制",
      copyFailedLabel: "请手动选择并复制命令",
      contentsLabel: "本页内容",
      relatedLabel: "相关教程",
      sections: [
        { id: "platforms", title: "平台能力", tone: "note", blocks: [{ type: "paragraph", text: "仓库记录了 macOS 用户图片编辑器。当前 Windows 包使用随附装饰资源，没有提供相同的选择器。" }] },
        { id: "prepare", title: "准备图片", blocks: [{ type: "list", items: ["macOS 支持 PNG、JPEG、HEIC、TIFF 或 WebP。", "源文件不超过 50 MB，处理后资源不超过 16 MB。", "建议宽度至少 2000px，这是一项构图建议。", "左侧尽量安静，并为原生标题保留足够明暗对比。"] }] },
        { id: "picker", title: "使用 Finder 选择器", blocks: [{ type: "code", language: "bash", code: "~/.codex/codex-dream-skin-studio/scripts/customize-theme-macos.sh" }, { type: "paragraph", text: "不带参数运行即可在 Finder 选择图片，编辑器会处理本地资源并更新主题配置。" }] },
        { id: "cli", title: "使用 macOS 命令行", blocks: [{ type: "code", language: "bash", code: "~/.codex/codex-dream-skin-studio/scripts/customize-theme-macos.sh \\\n  --image \"/path/to/image.png\" \\\n  --name \"My theme\" \\\n  --accent \"#7cff46\" \\\n  --secondary \"#36d7e8\" \\\n  --highlight \"#642a8c\"" }] },
        { id: "reload", title: "重新应用并检查可读性", blocks: [{ type: "paragraph", text: "更换图片后启动或重新应用 Dream Skin，同时检查主页和任务页。如果文字对比不足，请换用更安静的裁切或调整强调色。" }] },
      ],
      related: ["macos", "restore", "windows"],
    },
    restore: {
      key: "restore",
      seo: { title: "恢复 Codex 官方外观", description: "在 Windows 或 macOS 安全停止 Codex Dream Skin，并恢复 Codex 官方外观。" },
      eyebrow: "恢复教程",
      h1: "恢复 Codex 官方外观",
      summary: "使用对应平台记录的恢复流程，停止注入器、关闭本机 CDP 会话并重新打开官方应用。",
      sourceLabel: "打开恢复源码",
      issueLabel: "反馈恢复问题",
      copyLabel: "复制",
      copiedLabel: "已复制",
      copyFailedLabel: "请手动选择并复制命令",
      contentsLabel: "本页内容",
      relatedLabel: "相关教程",
      sections: [
        { id: "windows", title: "Windows 恢复", blocks: [{ type: "paragraph", text: "使用桌面 Restore 快捷方式，或运行仓库脚本。下面的参数只恢复安装时保存的外观项。" }, { type: "code", language: "powershell", code: ".\\scripts\\restore-dream-skin.ps1 -RestoreBaseTheme" }] },
        { id: "macos", title: "macOS 恢复", blocks: [{ type: "paragraph", text: "双击 Restore Codex Dream Skin.command，或运行安装后的恢复脚本。" }, { type: "code", language: "bash", code: "~/.codex/codex-dream-skin-studio/scripts/restore-dream-skin-macos.sh" }] },
        { id: "preserved", title: "会保留什么", blocks: [{ type: "list", items: ["官方 Codex 应用与签名", "对话、项目、宠物/插件和登录状态", "API Key、Base URL 和模型供应商设置", "Dream Skin 状态目录中的用户图片与日志，除非另行删除"] }] },
        { id: "verify", title: "验证恢复结果", blocks: [{ type: "paragraph", text: "确认 Codex 重新打开后不再显示主题，并且回环调试会话已经关闭。状态不明确时使用对应平台的验证或 doctor 脚本。" }] },
        { id: "failure", title: "恢复失败时", tone: "warning", blocks: [{ type: "paragraph", text: "不要先删除状态文件。保留日志和记录状态；脚本要求时再手动关闭无法验证的 Codex 进程，并在 GitHub Issue 中附上平台和完整错误。" }] },
      ],
      related: ["windows", "macos", "customize"],
    },
  },
};
